### ISSUE TITLE
Code for unsupervised behavior recognition from pose

### ISSUE THREAD

**Issue by lnguyen** [talmo/sleap-mit-tutorial#1]
IS the code for that available anywhere to look at? I watched the youtube video and it seems very interesting

**Comment by talmo** [comment]
Hi @lnguyen,

The unsupervised recognition is based off MotionMapper (https://github.com/gordonberman/MotionMapper).

Here's a couple of repos that are probably a bit more usable:

https://github.com/bermanlabemory/motionmapperpy
https://github.com/LINCellularNeuroscience/VAME  <-- different approach but works in a similar way
https://github.com/YttriLab/B-SOID

**Comment by lnguyen** [comment]
thank you!
